version: '3'

services:
  backend:
    image: node:16-alpine
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DATABASE=postgres
      - JWT_SECRET=secret
      - MINIO_ACCESS_KEY_ID=minio
      - MINIO_SECRET=minio123
      - MINIO_URL=http://minio:9000
    expose:
      - 3100
    ports:
      - 3100:3100
    working_dir:
      /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        cd nest_redone/packages/backend; npm run start:dev
  
  
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - nest_redone:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  redis:
    image: redis:7.0.8-alpine
    ports:
      - '6379:6379'

  minio:
   image: minio/minio:latest
   command: server --console-address ":9001" /data/
   ports:
     - "9000:9000"
     - "9001:9001"
   environment:
     MINIO_ROOT_USER: minio
     MINIO_ROOT_PASSWORD: minio123
   volumes:
     - minio-storage:/data
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3

volumes:
  nest_redone:
  minio-storage:
