version: '3'

services:
  backend:
    image: node:16-alpine
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DATABASE=postgres
      - JWT_SECRET=secret
    expose:
      - 3100
    ports:
      - 3100:3100
    working_dir:
      /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        cd nest_redone/packages/backend; npm run start:dev
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - nest_redone:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend_sockets:
    image: node:16-alpine
    environment:
      - DATABASE_HOST=database_sockets
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DATABASE=postgres
      - JWT_SECRET=secret
    ports:
      - 3101:3100
    working_dir:
      /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        cd nest_redone/packages/sockets; npm run start:dev

  database_sockets:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - nest_redone_sockets:/var/lib/postgresql/data


volumes:
  nest_redone:
  nest_redone_sockets: