version: '3.2'

services:
  server:
    image: node:18-alpine
    expose:
      - 4444
    working_dir:
      /app
    volumes:
      - ./server.js:/app/server.js
    ports:
      - 4444:4444
    command:
      - sh
      - -c
      - |
        node server.js
  
  nginx:
    image: nginx
    volumes:
    - ./docker-nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - ./docker-nginx/images:/data/images:delegated
    - ./docker-nginx/html:/data/html:cached
    - ./docker-nginx/upl:/data/upl
    - ./docker-nginx/hosts:/etc/hosts

    ports:
    - "80:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80

volumes:
  nginx: