version: '3.2'

services:
  nginx:
    image: nginx
    volumes:
    - ./docker-nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - ./docker-nginx/images:/data/images
    - ./docker-nginx/html:/data/html
    - ./docker-nginx/upl:/data/upl

    ports:
    - "80:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80

volumes:
  nginx: