version: '3'

services:
  backend_sockets:
    image: node:16-alpine
    environment:
      - DATABASE_HOST=database_sockets
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DATABASE=postgres
      - JWT_SECRET=secret
    expose:
      - 3100
    ports:
      - 3100:3100
      - 8080:8080
    working_dir:
      /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        cd nest_redone/packages/sockets; npm run start:dev

  database_sockets:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - nest_redone_sockets:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'


volumes:
  nest_redone_sockets:
