version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_PASS=$RABBIT_PASS"
      - "RABBITMQ_DEFAULT_USER=$RABBIT_USER"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge